/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.max.backgroundlinuxmanager.views.components;

/**
 *
 * @author max
 */
public class LibrayPanel extends javax.swing.JPanel {

    /**
     * Creates new form LibrayPanel
     */
    public LibrayPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollContent = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();

        setLayout(null);

        scrollContent.setBorder(null);
        scrollContent.setForeground(new java.awt.Color(222, 22, 222));
        scrollContent.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollContent.setToolTipText("");
        scrollContent.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        scrollContent.setAutoscrolls(true);
        scrollContent.setName(""); // NOI18N
        scrollContent.setVerifyInputWhenFocusTarget(false);
        add(scrollContent);
        scrollContent.setBounds(0, 53, 777, 566);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 200, 5));

        titleLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        titleLabel.setText("Library");
        titleLabel.setToolTipText("");
        jPanel1.add(titleLabel);

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 39);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addButton;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JScrollPane scrollContent;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
