/*
 * The MIT License
 *
 * Copyright 2019 Maximiliano Fernández <thebluemax13 at gmail.com>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.max.backgroundlinuxmanager.views.components;

import com.max.backgroundlinuxmanager.models.XMLDOMBackground;
import com.max.backgroundlinuxmanager.models.entities.SlideBackground;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ComboBoxModel;
import javax.swing.JPanel;
import org.jdesktop.swingx.JXDatePicker;


/**
 *
 * @author Maximiliano Fernández <thebluemax13 at gmail.com>
 */
public class SlideEditPanel extends javax.swing.JPanel {

    /**
     * Creates new form SlideEditPanel
     */
    private JPanel container;
    
    public SlideEditPanel(Dimension dimension) {
        initComponents();
        container = new JPanel(new GridLayout(0, 6));
        jScrollPane1.setPreferredSize(dimension);
         jScrollPane1.setViewportView(container);
        buildCombos();
        
       
        
    }
    private void buildCombos(){
        
        Calendar date = Calendar.getInstance();
        
        int year = date.get(Calendar.YEAR);
        
        
        int refYear = year - 10;
        
        for (int y = 0; y < 20; y++) {
            yearCombo.addItem(Integer.toString(refYear + y));
            
        }
        
        yearCombo.setSelectedItem(Integer.toString(year));
    
        for (int r = 0; r < 31; r++) {
            dayCombo.addItem(Integer.toString(r + 1));
            
        }
        for (int d = 0; d < 24; d++) {
            monthCombo.addItem(Integer.toString(d + 1));
            
        }
        for (int a = 0; a < 24; a++) {
            hourCombo.addItem(Integer.toString(a + 1));
            
        }
       
        for (int i = 0; i < 60; i++) {
            
             secondCombo.addItem(Integer.toString(i + 1));
             minuteCombo.addItem(Integer.toString(i + 1));
        }
    }
    
    protected void setValues(XMLDOMBackground slidemodel){
        SlideBackground back = slidemodel.getSlideBackground();
        
        System.err.println(back.getTime().get("year").toString());
        yearCombo.setSelectedItem(back.getTime().get("year").toString());
        monthCombo.setSelectedItem(back.getTime().get("month").toString());
        dayCombo.setSelectedItem(back.getTime().get("day").toString());
        hourCombo.setSelectedItem(back.getTime().get("hour").toString());
        minuteCombo.setSelectedItem(back.getTime().get("minute").toString());
         secondCombo.setSelectedItem(back.getTime().get("second").toString());
     //    float durationS = Float.parse(back.getImageDuration());
         duratonSlide.setValue(back.getImageDuration());
         transitionSlide.setValue(back.getTransitionDuration());
         
         slideName.setText(back.getName());
         slideName.setEditable(false);
    }
    
    protected void setMouseAdapter(MouseAdapter adapter){
        slideName.addMouseListener(adapter);
    }
    
    protected Dimension getContainerBounds(){
        return new Dimension(jScrollPane1.getWidth(),jScrollPane1.getHeight());
    }
    
    protected void addToPanel(Component comp){
        container.add(comp);
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        slideName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        duratonSlide = new javax.swing.JSlider();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        transitionSlide = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        yearCombo = new javax.swing.JComboBox<>();
        monthCombo = new javax.swing.JComboBox<>();
        dayCombo = new javax.swing.JComboBox<>();
        hourCombo = new javax.swing.JComboBox<>();
        minuteCombo = new javax.swing.JComboBox<>();
        secondCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();

        setLayout(new java.awt.GridBagLayout());

        slideName.setText("jTextField1");
        slideName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slideNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 535;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(slideName, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Duration Slide image");
        jPanel2.add(jLabel1);

        duratonSlide.setMaximum(2000);
        duratonSlide.setMinimum(6);
        duratonSlide.setPaintLabels(true);
        duratonSlide.setToolTipText("");
        jPanel2.add(duratonSlide);

        jPanel3.add(jPanel2);

        jPanel4.setLayout(new java.awt.GridLayout(2, 1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Duration Transition");
        jPanel4.add(jLabel3);

        transitionSlide.setMaximum(10);
        transitionSlide.setMinimum(1);
        jPanel4.add(transitionSlide);

        jPanel3.add(jPanel4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jPanel3, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridLayout(2, 5));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Year");
        jPanel1.add(jLabel5);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Month");
        jPanel1.add(jLabel6);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Day");
        jPanel1.add(jLabel7);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Hour");
        jPanel1.add(jLabel8);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Minute");
        jPanel1.add(jLabel9);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Seconds");
        jPanel1.add(jLabel10);

        jPanel1.add(yearCombo);

        jPanel1.add(monthCombo);

        jPanel1.add(dayCombo);

        jPanel1.add(hourCombo);

        jPanel1.add(minuteCombo);

        jPanel1.add(secondCombo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 118;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void slideNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slideNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slideNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dayCombo;
    private javax.swing.JSlider duratonSlide;
    private javax.swing.JComboBox<String> hourCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> minuteCombo;
    private javax.swing.JComboBox<String> monthCombo;
    private javax.swing.JComboBox<String> secondCombo;
    private javax.swing.JTextField slideName;
    private javax.swing.JSlider transitionSlide;
    private javax.swing.JComboBox<String> yearCombo;
    // End of variables declaration//GEN-END:variables
}
