/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.max.backgroundlinuxmanager.views.components;

import java.awt.Panel;
import javax.swing.JPanel;

/**
 *
 * @author max
 */
public class XmlWallpaperPanel extends javax.swing.JPanel {

    /**
     * Creates new form XmlWallpaperPanel
     */
    public XmlWallpaperPanel() {
        initComponents();
    }

    public void addToPanel(JPanel panel, int x, int y, int width, int heigth){
    add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, width, heigth) );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wallpaperCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wallpaperComboActionPerformed(evt);
            }
        });
        add(wallpaperCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void wallpaperComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wallpaperComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wallpaperComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public final javax.swing.JComboBox<String> wallpaperCombo = new javax.swing.JComboBox<>();
    // End of variables declaration//GEN-END:variables
}
