/*
 * The MIT License
 *
 * Copyright 2019 Maximiliano Fernández <thebluemax13 at gmail.com>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.max.backgroundlinuxmanager.views;

import java.io.File;
import com.max.backgroundlinuxmanager.controllers.utils.ImageManager;

/**
 *
 * @author Maximiliano Fernández <thebluemax13 at gmail.com>
 */
public class ImageBlockPane extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public ImageBlockPane() {
        initComponents();
        ImageHolder.setText("");
    }
    public void setIcon(File image) {
        ImageHolder.setIcon(ImageManager.resize(image, 120, 100));
        objectCheckbox.setLabel(image.getName());
    }
    public void setLabel(String label){
        objectCheckbox.setLabel(label);
    }
    public boolean isChecked (){
    return objectCheckbox.isSelected();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageHolder = new javax.swing.JLabel();
        objectCheckbox = new javax.swing.JCheckBox();
        erraseBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(46, 36, 57));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 3));
        setPreferredSize(new java.awt.Dimension(150, 150));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImageHolder.setBackground(new java.awt.Color(35, 24, 12));
        ImageHolder.setText("jLabel1");
        add(ImageHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 180, 120));

        objectCheckbox.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        objectCheckbox.setText("jCheckBox1");
        add(objectCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 110, 40));

        erraseBtn.setText("jButton1");
        add(erraseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 40, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageHolder;
    private javax.swing.JButton erraseBtn;
    private javax.swing.JCheckBox objectCheckbox;
    // End of variables declaration//GEN-END:variables
}
