/*
 * The MIT License
 *
 * Copyright 2019 Maximiliano Fernández <thebluemax13 at gmail.com>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.max.backgroundlinuxmanager.views;

import com.max.backgroundlinuxmanager.views.components.ListAndButtons;
import com.max.backgroundlinuxmanager.views.components.SidePanel;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.plaf.ColorUIResource;


/**
 *
 * @author Maximiliano Fernández <thebluemax13 at gmail.com>
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private static String ADD_TO_LIBRARY = "addToLibrary";
    private static String GET_WALLPAPER = "getWallPaper";
    private static String LIBRARY_TAG ="Libreria"; 

    private JPanel container;
    private File[] fileList;
    private DefaultListModel collectionName;
    private DefaultListModel wallpaperName;
    private SidePanel sideBar;

    public MainJFrame() {
        initComponents();
        this.getContentPane().setBackground( new Color(18,39,43) );
        sideBar = new SidePanel();
        sideBar.toggleLibrary(false);
        getContentPane().add(sideBar,  new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 500));
        container = new JPanel();
        container.setSize(600, 1024);
        container.setLayout(new GridLayout(0,3));
        jButton1.setActionCommand(ADD_TO_LIBRARY);
        scrollContent.setViewportView(container); 
    }
    public String getListElement(int index){
    return (String) collectionName.get(index);
    }
    public String getWallpaperName(int index){
    return (String) wallpaperName.get(index);
    } 
    public void setListeners(ActionListener aListener) {
    jButton1.addActionListener(aListener);
    }
    public void setViewPortContainer (JPanel jPane){
        scrollContent.setViewportView(jPane);
    }
    public void setLibraryView(boolean visibility){
        sideBar.toggleLibrary(visibility);
        if (visibility) {
       //     jList2.setVisible(false);
        //    jList2.setOpaque(false); 
            scrollContent.setViewportView(container);
            //jButton1.setEnabled(true);
            
        } else {
         //   jList2.setVisible(true);
            scrollContent.setViewportView(null);
           // jButton1.setEnabled(false);
           
        }
    }
    public void addToPanel (JPanel jp){
        container.add(jp);
    }
    public void setWallpaperList(String[] nameWallpaper){
       sideBar.setChildLidt(nameWallpaper);
     //   jList2.setModel(wallpaperName);
        //jTextPane1.setContentType("text/html");
    //jTextPane1.setText(text);
    }
    public void setList(String folder, String[] listFile){
        sideBar.setListFather(listFile);
       
        jLabel2.setText("Active Folder: "+folder);
        
    }
    public void addSideBarEvents(MouseAdapter mouseAdapter){
        sideBar.addListMouseEvents(mouseAdapter);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        navPanel = new javax.swing.JPanel();
        scrollContent = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Background Manager");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(18, 39, 93));
        setBounds(new java.awt.Rectangle(0, 0, 700, 500));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 44, 124));
        setLocation(new java.awt.Point(100, 100));
        setMaximumSize(new java.awt.Dimension(2147, 2147));
        setName("principalFrame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPanel.setBackground(new java.awt.Color(254, 254, 254));
        contentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        contentPanel.setOpaque(false);
        contentPanel.setLayout(new java.awt.GridLayout(1, 0));

        jButton4.setText("Add Wallpaper");
        jButton4.setToolTipText("Add to wallpaper whit default  options");
        contentPanel.add(jButton4);

        jButton5.setText("Add to Slide");
        contentPanel.add(jButton5);

        jButton6.setText("Save");
        jButton6.setName(""); // NOI18N
        jButton6.setOpaque(true);
        contentPanel.add(jButton6);

        jButton9.setText("Delete");
        contentPanel.add(jButton9);

        jButton1.setBackground(new java.awt.Color(57, 207, 57));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton1.setText("Load to Library");
        jButton1.setToolTipText("");
        jButton1.setActionCommand("load_to_library");
        jButton1.setAlignmentY(0.0F);
        jButton1.setAutoscrolls(true);
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        contentPanel.add(jButton1);

        getContentPane().add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 630, 60));

        navPanel.setOpaque(false);
        navPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        navPanel.add(scrollContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 430));

        getContentPane().add(navPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, 430));

        jLabel2.setBackground(new java.awt.Color(1, 1, 1));
        jLabel2.setForeground(new java.awt.Color(253, 251, 251));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setLabelFor(scrollContent);
        jLabel2.setText("jLabel2");
        jLabel2.setAutoscrolls(true);
        jLabel2.setBorder(null);
        jLabel2.setRequestFocusEnabled(false);
        jLabel2.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 630, 30));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  //*  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
   /*    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>/*/

        /* Create and display the form */
    //    java.awt.EventQueue.invokeLater(new Runnable() {
      //      public void run() {
      //          new MainJFrame().setVisible(true);
      //      }
      //  });
 //   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel navPanel;
    private javax.swing.JScrollPane scrollContent;
    // End of variables declaration//GEN-END:variables
}
