/*
 * The MIT License
 *
 * Copyright 2019 Maximiliano Fernández <thebluemax13 at gmail.com>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.max.backgroundlinuxmanager.views;

import com.max.backgroundlinuxmanager.controllers.events.WallpaperButtonAdapter;
import com.max.backgroundlinuxmanager.controllers.utils.ImageManager;
import com.max.backgroundlinuxmanager.models.entities.AppConfiguration;
import com.max.backgroundlinuxmanager.models.entities.Wallpaper;
import com.max.backgroundlinuxmanager.utils.ColorManager;
import com.max.backgroundlinuxmanager.utils.ManagerFiles;
import java.awt.Color;
import java.awt.Rectangle;
import java.awt.event.ComponentAdapter;
import java.awt.event.ContainerAdapter;
import java.awt.event.ContainerListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import javax.swing.ComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JList;
import javax.swing.plaf.basic.BasicSliderUI;

/**
 *
 * @author Maximiliano Fernández <thebluemax13 at gmail.com>
 */
public class WallpaperPanel extends javax.swing.JPanel {

    /**
     * Creates new form JpaneWallpaper
     */
    private Wallpaper wp;
    public static final String PCOLOR = "pcolor";
    public static final String SCOLOR = "scolor";
   
    public WallpaperPanel(Wallpaper wp) {
        this.wp = wp; 
        initComponents();
        nameLabel.setText(this.wp.getName());
        
        pathLabel.setText(ManagerFiles.getUserFolder()+"/"+wp.getFilename());
        File f = new File(ManagerFiles.getUserFolder()+"/"+wp.getFilename());
        imageHolder.setText("");
        imageHolder.setBounds(0, 0, 300,150);
       // controlPanel.setBounds(new Rectangle(300, 200));
        imageHolder.setIcon(ImageManager.resize(f, imageHolder.getWidth(), imageHolder.getHeight()));
        comboBuild();
        pcolor.setBackground(ColorManager.getColor(wp.getPcolor()));
        pcolor.setOpaque(true);
        pcolor.setName(PCOLOR);
        pcolor.setText(wp.getPcolor());
        scolor.setBackground(ColorManager.getColor(wp.getScolor()));
        scolor.setText(wp.getScolor());
        scolor.setName(SCOLOR);
        scolor.setOpaque(true);
        this.setBackground(ColorManager.getColor("#ff45ed"));
        System.out.println(this.getSize().height);
        WallpaperButtonAdapter adapter = new WallpaperButtonAdapter(wp);
        pcolor.addMouseListener(adapter);
        scolor.addMouseListener(adapter);
      //  pcolor.add
    }
    private void comboBuild() {
        
        String[] arr = AppConfiguration.OPTIONS_WALLPAPER;
        for (int i = 0; i < arr.length ; i++) {
            optionCombobox.addItem(arr[i]);
        }
        optionCombobox.setSelectedItem(wp.getOptions());
    }
    private Wallpaper getWallpaper(){
    return  wp;
    };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        nameLabel = new javax.swing.JLabel();
        imageHolder = new javax.swing.JLabel();
        controlPanel = new javax.swing.JPanel();
        optionLabel = new javax.swing.JLabel();
        optionCombobox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        shaderCombobox = new javax.swing.JComboBox<>();
        pcolor = new javax.swing.JLabel();
        pathLabel = new javax.swing.JLabel();
        scolor = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 500));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 400));
        setLayout(new java.awt.GridBagLayout());

        nameLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameLabel.setLabelFor(imageHolder);
        nameLabel.setText("jLabel6");
        nameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        nameLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        add(nameLabel, gridBagConstraints);

        imageHolder.setText("jLabel1");
        imageHolder.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        add(imageHolder, gridBagConstraints);

        controlPanel.setLayout(new java.awt.GridLayout(4, 2, 5, 0));

        optionLabel.setText("Options");
        controlPanel.add(optionLabel);

        optionCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionComboboxActionPerformed(evt);
            }
        });
        controlPanel.add(optionCombobox);

        jLabel1.setText("Type Shader");
        controlPanel.add(jLabel1);

        shaderCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        shaderCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shaderComboboxActionPerformed(evt);
            }
        });
        controlPanel.add(shaderCombobox);

        pcolor.setText("jLabel3");
        controlPanel.add(pcolor);

        pathLabel.setText("jLabel5");
        controlPanel.add(pathLabel);

        scolor.setText("jLabel4");
        controlPanel.add(scolor);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 9, 5, 9);
        add(controlPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void optionComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionComboboxActionPerformed

    private void shaderComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shaderComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shaderComboboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel imageHolder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JComboBox<String> optionCombobox;
    private javax.swing.JLabel optionLabel;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JLabel pcolor;
    private javax.swing.JLabel scolor;
    private javax.swing.JComboBox<String> shaderCombobox;
    // End of variables declaration//GEN-END:variables
}
