/*
 * The MIT License
 *
 * Copyright 2019 Maximiliano Fernández <thebluemax13 at gmail.com>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.max.backgroundlinuxmanager.views;

import com.max.backgroundlinuxmanager.controllers.utils.ImageManager;
import com.max.backgroundlinuxmanager.models.entities.AppConfiguration;
import com.max.backgroundlinuxmanager.models.entities.Wallpaper;
import com.max.backgroundlinuxmanager.utils.ManagerFiles;
import java.io.File;
import javax.swing.ComboBoxModel;
import javax.swing.JList;

/**
 *
 * @author Maximiliano Fernández <thebluemax13 at gmail.com>
 */
public class WallpaperPanel extends javax.swing.JPanel {

    /**
     * Creates new form JpaneWallpaper
     */
    private Wallpaper wp;
   
    public WallpaperPanel(Wallpaper wp) {
        this.wp = wp; 
        initComponents();
        nameLabel.setText(this.wp.getName());
        
        pathLabel.setText(ManagerFiles.getUserFolder()+"/"+wp.getFilename());
        File f = new File(ManagerFiles.getUserFolder()+"/"+wp.getFilename());
        imageHolder.setText("");
        imageHolder.setBounds(0, 0, 410,400);
        imageHolder.setIcon(ImageManager.resize(f, imageHolder.getWidth(), imageHolder.getHeight()));
        comboBuild();
        
    }
    private void comboBuild() {
        
        String[] arr = AppConfiguration.OPTIONS_WALLPAPER;
        for (int i = 0; i < arr.length ; i++) {
            optionCombobox.addItem(arr[i]);
        }
        optionCombobox.setSelectedItem(wp.getOptions());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageHolder = new javax.swing.JLabel();
        optionCombobox = new javax.swing.JComboBox<>();
        optionLabel = new javax.swing.JLabel();
        pcolor = new javax.swing.JLabel();
        scolor = new javax.swing.JLabel();
        pathLabel = new javax.swing.JLabel();
        shaderCombobox = new javax.swing.JComboBox<>();
        nameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imageHolder.setText("jLabel1");
        add(imageHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 340, 160));

        optionCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionComboboxActionPerformed(evt);
            }
        });
        add(optionCombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 90, -1));

        optionLabel.setText("Options");
        add(optionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 100, -1));

        pcolor.setText("jLabel3");
        add(pcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 31));

        scolor.setText("jLabel4");
        add(scolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 170, -1));

        pathLabel.setText("jLabel5");
        add(pathLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        shaderCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        shaderCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shaderComboboxActionPerformed(evt);
            }
        });
        add(shaderCombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 100, -1));

        nameLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        nameLabel.setText("jLabel6");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 4, 360, 30));

        jLabel1.setText("Type Shader");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void optionComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionComboboxActionPerformed

    private void shaderComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shaderComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shaderComboboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageHolder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JComboBox<String> optionCombobox;
    private javax.swing.JLabel optionLabel;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JLabel pcolor;
    private javax.swing.JLabel scolor;
    private javax.swing.JComboBox<String> shaderCombobox;
    // End of variables declaration//GEN-END:variables
}
