/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.max.backgroundlinuxmanager.components.XmlWallpaperComponent;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 *
 * @author max
 */
public class XmlPanelNav extends javax.swing.JPanel implements ItemListener {

    
    /**
     * Creates new form XmlPanelNav
     */
    public XmlPanelNav() {
        initComponents();
    }
/**
 * 
 * @param filemanes Strimg[]
 * @return void
 */
    public String poblateCombo(String[] filemanes) {
        for (String filemane : filemanes) {
            wallpaperCombo.addItem(filemane);
        }
        return (String) wallpaperCombo.getItemAt(0);
        //   buildWallpapers(activeWallpaperName);
    }
    /**
     *
     * @param e ItemEvent
     */
    @Override
    public void itemStateChanged(ItemEvent e) {
        System.out.println("Selected" + e.getStateChange());
        if (e.getSource() == wallpaperCombo && e.getStateChange() == 1) {
            //  buildWallpapers((String) wallpaperCombo.getSelectedItem());
            // clear();
            //   seeWallpaper();
            System.out.println((String) wallpaperCombo.getSelectedItem());
            // buildWallpapers(String filename)
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        newXmlWallpaperBtn = new javax.swing.JButton();
        cancellWallpaperBtn = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        newXmlWallpaperBtn.setText("ADD NEW");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(newXmlWallpaperBtn, gridBagConstraints);

        cancellWallpaperBtn.setText("ADD NEW");
        cancellWallpaperBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancellWallpaperBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(cancellWallpaperBtn, gridBagConstraints);

        wallpaperCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wallpaperComboActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 198;
        add(wallpaperCombo, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cancellWallpaperBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancellWallpaperBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancellWallpaperBtnActionPerformed

    private void wallpaperComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wallpaperComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wallpaperComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton cancellWallpaperBtn;
    protected javax.swing.JButton newXmlWallpaperBtn;
    public final javax.swing.JComboBox<String> wallpaperCombo = new javax.swing.JComboBox<>();
    // End of variables declaration//GEN-END:variables

}
